version: '3.1'

networks:
  network-zabbix-pg:
    driver: bridge

services:

  zabbix-server:
    container_name: zabbix-server-pg
    image: zabbix/zabbix-server-pgsql
    networks:
      - network-zabbix-pg
    restart: always
    ports:
      - ${DB_SERVER_PORT}:10051
    environment:
      - DB_SERVER_HOST=${DB_SERVER_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_SERVER_PORT=${DB_SERVER_PORT}
