version: '2.4'
services:
  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-pgsql:ol-6.4-latest
    restart: always
    pull_policy: always
    environment:
      - DB_SERVER_HOST=10.0.200.10
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=SENHA
    volumes:
      - /srv/volumes/zabbix-server-module:/var/lib/zabbix/modules
    networks:
      zabbix-rede:
        ipv4_address: '10.0.200.7'

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-apache-pgsql:ol-6.4-latest
    restart: always
    pull_policy: always
    environment:
      - DB_SERVER_HOST=10.0.200.10
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=SENHA
      - ZBX_SERVER_HOST=10.0.200.7
      - PHP_TZ=America/Sao_Paulo
    networks:
      zabbix-rede:
        ipv4_address: '10.0.200.8'
    ports:
      - 8080:8080
      - 443:8443
    volumes:
      - /srv/volumes/zabbix-frontend/ssl.key:/etc/ssl/apache2/ssl.key
      - /srv/volumes/zabbix-frontend/ssl.crt:/etc/ssl/apache2/ssl.crt

  zabbix-pgsql:
    container_name: zabbix-pgsql
    image: postgres:15.1-bullseye
    restart: always
    environment:
      - POSTGRES_PASSWORD=SENHA
    volumes:
      - type: volume
        source: data
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    networks:
      zabbix-rede:
        ipv4_address: '10.0.200.10'
    ports:
      - 5432:5432

  grafana:
    container_name: grafana
    image: grafana/grafana
    networks:
      - zabbix-rede
    links:
      - zabbix-pgsql
      - zabbix-server
    restart: always
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    depends_on:
      - zabbix-pgsql
      - zabbix-server

  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent:ol-6.4-latest
    user: root
    networks:
      - zabbix-rede
    links:
      - zabbix-server
    restart: always
    privileged: true
    volumes:
      - type: volume
        source: data_zabbix-agent
        target: /var/run
        volume:
          nocopy: true
    ports:
      - 10050:10050
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST=10.0.200.7

networks:
  zabbix-rede:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.200.0/24
          gateway: '10.0.200.1'
volumes:
  data:
  data_zabbix-agent:


